version: "3.7"
services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: ./docker/app/Dockerfile
        container_name: app
        restart: always
        volumes:
            - .:/var/www
        networks:
            - appnetwork

    db:
        image: postgres
        container_name: db
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/conf/db/:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
        networks:
            - appnetwork

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5050:80"
        networks:
            - appnetwork

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        volumes:
            - .:/var/www
            - ./docker/conf/nginx:/etc/nginx/conf.d
        ports:
            - 8080:80
        networks:
            - appnetwork

networks:
    appnetwork:
        driver: bridge
